# What is TensorFlow?

![](https://upload.wikimedia.org/wikipedia/commons/a/a4/TensorFlowLogo.png)


TensorFlow is an open source software library released in 2015 by Google to make it easier for developers to design, build, and train deep learning models. TensorFlow originated as an internal library that Google developers used to build models in-house, and we expect additional functionality to be added to the open source version as they are tested and vetted in the internal flavor. Although TensorFlow is only one of several options available to developers, we choose to use it here because of its thoughtful design and ease of use. We’ll briefly compare TensorFlow to alternatives in the next section.

At a high level, TensorFlow is a Python library that allows users to express arbitrary computation as a graph of data flows. Nodes in this graph represent mathematical operations, whereas edges represent data that is communicated from one node to another. Data in TensorFlow are represented as tensors, which are multidimensional arrays. Although this framework for thinking about computation is valuable in many different fields, TensorFlow is primarily used for deep learning in practice and research.



## Install
As usual, we'll be using Conda to install TensorFlow. You might already have a TensorFlow environment, but check to make sure you have all the necessary packages.

### OS X or Linux
Run the following commands to setup your environment:

    conda create -n tensorflow python=3.5
    source activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Windows
And installing on Windows. In your console or Anaconda shell,

    conda create -n tensorflow python=3.5
    activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Hello, world!
Try running the following code in your Python console to make sure you have TensorFlow properly installed. The console will print "Hello, world!" if TensorFlow is installed. Don’t worry about understanding what it does. You’ll learn about it in the next section.



In [ ]:
lecture link : https://www.youtube.com/watch?v=8xSob_Y_Q-A&feature=youtu.be

In [2]:
import tensorflow as tf

In [2]:
tf.__version__

'1.14.0'

In [3]:
hello_constant = tf.constant('Hello World!')
hello_constant

<tf.Tensor 'Const:0' shape=() dtype=string>

TF does Lazy evaluation, unless i am trying to print the data, it will not execute it

In [4]:
import tensorflow as tf

# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
        # Run the tf.constant operation in the session
        output = sess.run(hello_constant)
        print(output)

b'Hello World!'


Let’s analyze the Hello World script you ran. 

### Tensor
In TensorFlow, data isn’t stored as integers, floats, or strings. These values are encapsulated in an object called a tensor. In the case of hello_constant = tf.constant('Hello World!'), hello_constant is a 0-dimensional string tensor, but tensors come in a variety of sizes as shown below:

In [5]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234)

# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789])

# C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

In [7]:
C 

<tf.Tensor 'Const_4:0' shape=(2, 3) dtype=int32>

In [8]:
with tf.Session() as sess:
  output=sess.run(C)


Always execute everything inside session.Session limits the use of reources,as and when it is required to use. But in tensor 2.x, the concept of session is handled internally, so no need to explicitly perform the operation

In [9]:
output

array([[123, 456, 789],
       [222, 333, 444]])

In [10]:
print(output)

[[123 456 789]
 [222 333 444]]


tf.constant() is one of many TensorFlow operations you will use in this lesson. The tensor returned by tf.constant() is called a constant tensor, because the value of the tensor never changes.

### Session

TensorFlow’s api is built around the idea of a computational graph, a way of visualizing a mathematical process.  Let’s take the TensorFlow code and turn that into a graph:

![Session](https://d17h27t6h515a5.cloudfront.net/topher/2016/October/580feadb_session/session.png)

A "TensorFlow Session", as shown above, is an environment for running a graph. The session is in charge of allocating the operations to GPU(s) and/or CPU(s), including remote machines. Let’s see how you use it:

In [27]:
with tf.Session() as sess:
    output = sess.run(hello_constant)

The code has already created the tensor, `hello_constant`, from the previous lines. The next step is to evaluate the tensor in a session.

The code creates a session instance, `sess`, using `tf.Session`. The `sess.run()` function then evaluates the tensor and returns the results.

## TensorFlow Input 

In the last section, a tensor was passed into a session and it returned the result. What if we want to use a non-constant? This is where `tf.placeholder()` and `feed_dict` come into place. In this section, we'll go over the basics of feeding data into TensorFlow.

### tf.placeholder()

Sadly you can’t just set `x` to your dataset and put it in TensorFlow, because over time you'll want your TensorFlow model to take in different datasets with different parameters. You need `tf.placeholder()`!

`tf.placeholder()` returns a tensor that gets its value from data passed to the `tf.session.run()` function, allowing you to set the input right before the session runs.

### Session's feed_dict

In [11]:
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'sudh'})
    print(output)

sudh


Use the feed_dict parameter in `tf.session.run()` to set the placeholder tensor. The above example shows the tensor `x` being set to the string `"Hello, world"`. It's also possible to set more than one tensor using `feed_dict` as shown below:

In case of constant , data is passed at the time of variable creation , but in placeholder , we need to just mention the data type of the variable at RUNTIME

In [12]:
with tf.Session() as sess:
  output=sess.run(x, feed_dict={x: 9})
  print(output)

TypeError: Type of feed value 9 with type <class 'int'> is not compatible with Tensor type <class 'object'>. Try explicitly setting the type of the feed tensor to a larger type (e.g. int64).

Error as String has been declared at the time of variable creation

In [13]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x,feed_dict={x: 'Test String', y: 123, z: 45.67})
    output_y = sess.run(y, feed_dict={x: 'Test String', y: 123, z:45.67})
    print(output_x)
    print(output_y)

Test String
123


Do not have to necessarily mention all the variables in the dict, it extracts the necessary item

    output_y = sess.run(y, feed_dict={y: 123})
    
    this will work just fine


**Note**: If the data passed to the `feed_dict` doesn’t match the tensor type and can’t be cast into the tensor type, you’ll get the error `“ValueError: invalid literal for...”`.


## TensorFlow Math

Getting the input is great, but now you need to use it. We're going to use basic math functions that everyone knows and loves - add, subtract, multiply, and divide - with tensors. (There's many more math functions you can check out in the [documentation](https://www.tensorflow.org/api_docs/python/math_ops/).)

### Addition

In [15]:
x = tf.add(5, 2)  # 7
with tf.Session() as sess:
    output = sess.run(x)
    print(output)

7


Let's start with the add function. The `tf.add()` function does exactly what you expect it to do. It takes in two numbers, two tensors, or one of each, and returns their sum as a tensor.

### Subraction and Multiplication

In [14]:
x = tf.subtract(10, 4) # 6
y = tf.multiply(2, 5)  # 10

The `x` tensor will evaluate to `6`, because `10 - 4 = 6`. The `y` tensor will evaluate to `10`, because `2 * 5 = 10`. That was easy!

### Converting Types

It may be necessary to convert between types to make certain operators work together. For example, if you tried the following, it would fail with an exception:

In [16]:
tf.subtract(tf.constant(2.0),tf.constant(1))  

TypeError: Input 'y' of 'Sub' Op has type int32 that does not match type float32 of argument 'x'.

That's because the constant `1` is an integer but the constant `2.0` is a floating point value and subtract expects them to match.

In cases like these, you can either make sure your data is all of the same type, or you can cast a value to another type. In this case, converting the `2.0` to an integer before subtracting, like so, will give the correct result:

In [17]:
c = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # 1
with tf.Session() as sess:
    output = sess.run(c)
    print(output)

1


in the below code i tried to subtract int 32(1) from int 64(2.0) , but it still gives error

In [20]:
c = tf.subtract(tf.cast(tf.constant(2.0), tf.int64), tf.cast(tf.constant(1),tf.int32))   # 1
with tf.Session() as sess:
    output = sess.run(c)
    print(output)

TypeError: Input 'y' of 'Sub' Op has type int32 that does not match type int64 of argument 'x'.

### Example

Let's apply what you learned to convert an algorithm to TensorFlow. The code below is a simple algorithm using division and subtraction. Convert the following algorithm in regular Python to TensorFlow and print the results of the session. You can use `tf.constant()` for the values `10`, `2`, and `1`.

In [18]:
import tensorflow as tf


x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x, y), 1)


with tf.Session() as sess:
    output = sess.run(z)
    print(output)


4.0


## TensorFlow Linear Functions

The most common operation in neural networks is calculating the linear combination of inputs, weights, and biases. As a reminder, we can write the output of the linear operation as:

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58a4d8b3_linear-equation/linear-equation.gif)

Here, **W** is a matrix of the weights connecting two layers. The output **y**, the input **x**, and the biases **b** are all vectors.

### Weights and Bias in TensorFlow

The goal of training a neural network is to modify weights and biases to best predict the labels. In order to use weights and bias, you'll need a Tensor that can be modified. This leaves out `tf.placeholder()` and `tf.constant()`, since those Tensors can't be modified. This is where `tf.Variable` class comes in.

### tf.Variable()

In [3]:
x = tf.Variable(5)

The `tf.Variable` class creates a tensor with an initial value that can be modified, much like a normal Python variable. This tensor stores its state in the session, so you must initialize the state of the tensor manually. You'll use the `tf.global_variables_initializer()` function to initialize the state of all the Variable tensors:

In [4]:
init = tf.global_variables_initializer() #only used tensorflow 1 version, use to make the varable available to the code
with tf.Session() as sess:
    sess.run(init)
    #this is mandatory when creating a variable

In [5]:
init

<tf.Operation 'init' type=NoOp>

The `tf.global_variables_initializer()` call returns an operation that will initialize all TensorFlow variables from the graph. You call the operation using a session to initialize all the variables as shown above. Using the `tf.Variable` class allows us to change the weights and bias, but an initial value needs to be chosen.

Initializing the weights with random numbers from a normal distribution is good practice. Randomizing the weights helps the model from becoming stuck in the same place every time you train it. You'll learn more about this in the next lesson, gradient descent.

Similarly, choosing weights from a normal distribution prevents any one weight from overwhelming other weights. We'll use the `tf.truncated_normal()` function to generate random numbers from a normal distribution.

### tf.truncated_normal()

In [6]:
n_features = 120 
n_labels = 5  #considering input of 120 neurons and output of 5 neurons
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))

weights

<tf.Variable 'Variable_1:0' shape=(120, 5) dtype=float32_ref>

In [7]:
with tf.Session() as sess:
    
    o= tf.Variable(tf.truncated_normal((n_features, n_labels)))
    print(o)

<tf.Variable 'Variable_2:0' shape=(120, 5) dtype=float32_ref>


The `tf.truncated_normal()` function returns a tensor with random values from a normal distribution whose magnitude is no more than 2 standard deviations from the mean.

Since the weights are already helping prevent the model from getting stuck, you don't need to randomize the bias. Let's use the simplest solution, setting the bias to 0.

### tf.zeros()

In [16]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))

The `tf.zeros()` function returns a tensor with all zeros.

## TensorFlow Softmax

The softmax function squashes it's inputs, typically called **logits** or **logit scores**, to be between 0 and 1 and also normalizes the outputs such that they all sum to 1. This means the output of the softmax function is equivalent to a categorical probability distribution. It's the perfect function to use as the output activation for a network predicting multiple classes.

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58950908_softmax-input-output/softmax-input-output.png)

We're using TensorFlow to build neural networks and, appropriately, there's a function for calculating softmax.

In [7]:
x = tf.nn.softmax([2.0, 1.0, 0.2])
with tf.Session() as sess:
    output = sess.run(x)
    print(output)

[0.65223986 0.23994564 0.10781453]


Easy as that! `tf.nn.softmax()` implements the softmax function for you. It takes in logits and returns softmax activations.

### Example

In [8]:
import tensorflow as tf


def run_2():
    output = None
    logit_data = [19,354,354,45,354,54]
    logits = tf.placeholder(tf.float32)
    
    # Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)   
    
    with tf.Session() as sess:
        # Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

print(run_2())

[0.         0.33333334 0.33333334 0.         0.33333334 0.        ]


## One-Hot Encoding

Transforming your labels into one-hot encoded vectors is pretty simple with scikit-learn using `LabelBinarizer`. Check it out below!

In [9]:
import numpy as np
from sklearn import preprocessing

l=np.array([1,2,4,6,4,1,1,2])

lb=preprocessing.LabelBinarizer()

lb.fit(l)



LabelBinarizer(neg_label=0, pos_label=1, sparse_output=False)

In [10]:
lb.transform(l)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [11]:
l=np.array([6,2,4,1,4,1,1,2])

lb=preprocessing.LabelBinarizer()

lb.fit(l)

lb.transform(l) #note the encoing takes the order into consideration

array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [13]:
l=np.array(['d','a','b'])

lb=preprocessing.LabelBinarizer()

lb.fit(l)

lb.transform(l)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

## TensorFlow Cross Entropy

In the Intro to TFLearn lesson we discussed using cross entropy as the cost function for classification with one-hot encoded labels. Again, TensorFlow has a function to do the cross entropy calculations for us.

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/589b18f5_cross-entropy-diagram/cross-entropy-diagram.png)

To create a cross entropy function in TensorFlow, you'll need to use two new functions:

* `tf.reduce_sum()`
* `tf.log()`

### Reduce Sum

In [19]:
x = tf.reduce_sum([1, 2, 3, 4, 5])  # 15

The `tf.reduce_sum()` function takes an array of numbers and sums them together.

### Natural Log

In [20]:
l = tf.log(100.0)  # 4.60517

This function does exactly what you would expect it to do. `tf.log()` takes the natural log of a number.

### Example

Print the cross entropy using `softmax_data` and `one_hot_encod_label`.

In [14]:
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as session:
    output = session.run(cross_entropy, feed_dict={one_hot: one_hot_data, softmax: softmax_data})
    print(output)


0.35667497


Keras : High level API on top of a tensorflow

NOte : Whenever we are inserting data into a beural network it will be in the form of an array

Keras example utilization: Note code is notworking due to installation issues

In [1]:
import numpy as np
import pandas as pd
from keras.model import Sequential
from keras.layer import Dense
from keras.wrapper.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from keras.preprocessing import StandardScalar
from keras.pipeline import Pipeline

Using TensorFlow backend.


TypeError: expected bytes, Descriptor found

In [5]:
import os
os.getcwd()

'C:\\Users\\Somnath\\Downloads'

In [8]:
df=pd.read_csv("housing.csv",delim_whitespace=True,header=None)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 2, saw 2


In [29]:
df=pd.read_csv("housing.csv",delim_whitespace=True,header=None,error_bad_lines=False)

b'Skipping line 2: expected 1 fields, saw 2\nSkipping line 3: expected 1 fields, saw 2\nSkipping line 4: expected 1 fields, saw 2\nSkipping line 5: expected 1 fields, saw 2\nSkipping line 6: expected 1 fields, saw 2\nSkipping line 7: expected 1 fields, saw 2\nSkipping line 8: expected 1 fields, saw 2\nSkipping line 9: expected 1 fields, saw 2\nSkipping line 10: expected 1 fields, saw 2\nSkipping line 11: expected 1 fields, saw 2\nSkipping line 12: expected 1 fields, saw 2\nSkipping line 13: expected 1 fields, saw 2\nSkipping line 14: expected 1 fields, saw 2\nSkipping line 15: expected 1 fields, saw 2\nSkipping line 16: expected 1 fields, saw 2\nSkipping line 17: expected 1 fields, saw 2\nSkipping line 18: expected 1 fields, saw 2\nSkipping line 19: expected 1 fields, saw 2\nSkipping line 20: expected 1 fields, saw 2\nSkipping line 21: expected 1 fields, saw 2\nSkipping line 22: expected 1 fields, saw 2\nSkipping line 23: expected 1 fields, saw 2\nSkipping line 24: expected 1 fields, s

In [30]:
df.head()

0
0  longitude,latitude,housing_median_age,total_ro...
1  -121.92,37.64,46.0,1280.0,209.0,512.0,208.0,5....
2  -121.9,37.66,18.0,7397.0,1137.0,3126.0,1115.0,...
3  -121.88,37.68,23.0,2234.0,270.0,854.0,286.0,7....
4  -121.88,37.67,16.0,4070.0,624.0,1543.0,577.0,6...

Do note that using error_bad_lines=False will cause the offending lines to be skipped

In [31]:
dataset=df.values
#Values represents the data in the form of an array , which is used to input the neural network

dataset

array([['longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity'],
       ['-121.92,37.64,46.0,1280.0,209.0,512.0,208.0,5.1406,315600.0,INLAND'],
       ['-121.9,37.66,18.0,7397.0,1137.0,3126.0,1115.0,6.4994,323000.0,INLAND'],
       ...,
       ['-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7,92300.0,INLAND'],
       ['-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND'],
       ['-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND']],
      dtype=object)

In [32]:
sorted(df)

[0]

In [33]:
X=dataset[:,0:13]
Y=dataset[:,13]

IndexError: index 13 is out of bounds for axis 1 with size 1

This is a simple model with single fully connected hiddn layer , with the same number of imputs as the number of neurons, since here regression is being used no acivation function is utilized

ADAM optimiserand MSE is being used

In [ ]:
def baseline_model():
    model=Sequential()
    model.add(Dense(13,input_dim=13,init='normal',activation='relu'))
    #13==> stands for 13 perceptrons on the hiden layer and input_dim=13 stands for 13 inputs
    # Note : number of inputs does not matter it could even be 5 inputs 
    #init='normal'means whatever wight that is randomly initialized has to be normally distributed
    model.add(Dense(1,init='normal'))
    #creating another layer having number of neurons=1 (Since this is a regression, no activation problem is given here**)
    model.compile(loss='mean_squared_error',optimization='adam')
    return model   

In [ ]:
estimator=KerasRegressor(build_fn='baseline_model',nb_epoch=100,batch_size=5,verbose=0)
#for classification problem , would have called a classifier
#verbose=1==> will print **
estimator

In [ ]:
estimator.fit(X,Y)

In [ ]:
pred=estimator.predict(X)
pred

## Mini-batching


Mini-batching is a technique for training on subsets of the dataset instead of all the data at one time. This provides the ability to train a model, even if a computer lacks the memory to store the entire dataset.

Mini-batching is computationally inefficient, since you can't calculate the loss simultaneously across all samples. However, this is a small price to pay in order to be able to run the model at all.

It's also quite useful combined with SGD. The idea is to randomly shuffle the data at the start of each epoch, then create the mini-batches. For each mini-batch, you train the network weights with gradient descent. Since these batches are random, you're performing SGD with each batch.



## Epochs

An epoch is a single forward and backward pass of the whole dataset. This is used to increase the accuracy of the model without requiring more data. 